name:                soundwaves
version:             0.1.0.0
github:              "leonlbc/haskell-soundwave-gen"
license:             BSD3
author:              "Leon Cohen"
maintainer:          "cohenleonlbc@gmail.com"
copyright:           "2023 Leon Cohen"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/leonlbc/haskell-soundwave-gen>

dependencies:
- base >= 4.7 && < 5
- bytestring
- process

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  soundwaves-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - soundwaves
